-- Code generated by protoc-gen-haskell 0.1.0, DO NOT EDIT.
{-# LANGUAGE DerivingVia, DeriveAnyClass, DuplicateRecordFields #-}
module Twirp.Example.HaberdasherPB where

import Data.Aeson
import Data.Int
import Data.Text (Text)
import Data.Word
import GHC.Generics
import Proto3.Suite

data Size = Size
  { inches :: Int32
  } deriving stock (Eq, Show, Generic)
    deriving anyclass (Message, Named, FromJSON, ToJSON)

data Hat = Hat
  { inches :: Int32
  , color :: String
  , name :: String
  } deriving stock (Eq, Show, Generic)
    deriving anyclass (Message, Named, FromJSON, ToJSON)

data Bill = Bill
  { price :: Maybe Price
  , status :: BillingStatus
  } deriving stock (Eq, Show, Generic)
    deriving anyclass (Message, Named, FromJSON, ToJSON)

data BillingStatus
  = UnPaid
  | Paid
  deriving stock (Eq, Ord, Show, Enum, Bounded, Generic)
  deriving anyclass (Named, MessageField, FromJSON, ToJSON)
  deriving Primitive via PrimitiveEnum BillingStatus
instance HasDefault BillingStatus where def = Paid

data Price = Price
  { dollars :: Word32
  , cents :: Word32
  } deriving stock (Eq, Show, Generic)
    deriving anyclass (Message, Named, FromJSON, ToJSON)
