-- Code generated by protoc-gen-twirp_haskell 0.1.0, DO NOT EDIT.
{-# LANGUAGE TypeOperators #-}
module Twirp.Example.Haberdasher where

import Servant
import Twirp

import Twirp.Example.HaberdasherPB

type HaberdasherAPI headers
  = "twirp" :> "twirp.example.haberdasher.Haberdasher" :> HaberdasherService headers

type HaberdasherService headers
  = "MakeHat" :> headers :> ReqBody [Protobuf, JSON] Size :> Post '[Protobuf, JSON] Hat
