#!/bin/bash
#/ Usage: script/protoc
#/
#/ Generate from Haskell code from .proto files.

set -e
cd "$(dirname "$0")/.."

# Compile haskell.proto (extensions to protoc)
protoc --proto_path=./internal/gen/haskell \
  --go_out=./internal/gen/haskell \
  haskell.proto

protoc --proto_path=./proto \
  --plugin=protoc-gen-twirp_haskell=./script/run-twirp_haskell --twirp_haskell_out=./app/Twirp/Example/Haberdasher \
  --plugin=protoc-gen-haskell=./script/run-haskell --haskell_out=./app/Twirp/Example/Haberdasher \
  haberdasher.proto

protoc -I=. --proto_path=./proto \
  --plugin=protoc-gen-twirp_haskell=./script/run-twirp_haskell --twirp_haskell_out=./app/Twirp/Example/Haberdasher \
  --plugin=protoc-gen-haskell=./script/run-haskell --haskell_out=./app/Twirp/Example/Haberdasher \
  wrapping.proto

# # stack exec compile-proto-file -- --out . --includeDir ./proto --proto haberdasher.proto
#
# Generate a python client
PYTHON_CLIENT_PATH=./clients/python/haberdasher
protoc --proto_path=./proto \
  --python_out="$PYTHON_CLIENT_PATH" \
  --twirp_python_out="$PYTHON_CLIENT_PATH" \
  ./proto/haberdasher.proto
