#!/bin/bash
#/ Usage: script/protoc
#/
#/ Generate from Haskell code from .proto files.

set -e
cd "$(dirname "$0")/.."

protoc --proto_path=./proto \
  --plugin=protoc-gen-twirp_haskell=./script/run-twirp_haskell --twirp_haskell_out=./app/Twirp/Example/Haberdasher \
  --plugin=protoc-gen-haskell=./script/run-haskell --haskell_out=./app/Twirp/Example/Haberdasher \
  ./proto/haberdasher.proto

# stack exec compile-proto-file -- --out . --includeDir ./proto --proto haberdasher.proto

# Generate a python client
PYTHON_CLIENT_PATH=./clients/python/haberdasher
protoc --proto_path=./proto \
  --python_out="$PYTHON_CLIENT_PATH" \
  --twirp_python_out="$PYTHON_CLIENT_PATH" \
  ./proto/haberdasher.proto
