-- Code generated by protoc-gen-twirp_haskell 0.1.0, DO NOT EDIT.
{-# LANGUAGE TypeOperators #-}
module Twirp.Example.Haberdasher.Haberdasher where

import Servant
import Twirp

import Proto.Haberdasher

--  This is an example set of twirp services.

type HaberdasherAPI
  =    "twirp" :> "twirp.example.haberdasher.Haberdasher" :> HaberdasherService
  :<|> "twirp" :> "twirp.example.haberdasher.Health" :> HealthService

--  Haberdasher service makes hats for clients.
type HaberdasherService
  --  MakeHat produces a hat of mysterious, randomly-selected color!
  =    "MakeHat" :> ReqBody [Protobuf, JSONPB] Size :> Post '[Protobuf, JSONPB] Hat
  --  Get paid
  :<|> "GetBill" :> ReqBody [Protobuf, JSONPB] Hat :> Post '[Protobuf, JSONPB] Bill

--  Health check service
type HealthService
  =    "Check" :> ReqBody [Protobuf, JSONPB] Ping :> Post '[Protobuf, JSONPB] Pong
