-- Code generated by protoc-gen-twirp_haskell 0.1.0, DO NOT EDIT.
{-# LANGUAGE TypeOperators #-}
module Twirp.Example.Haberdasher.Haberdasher where

import Servant
import Twirp

import Twirp.Example.Haberdasher.HaberdasherPB

type HaberdasherAPI headers
  =    "twirp" :> "twirp.example.haberdasher.Haberdasher" :> HaberdasherService headers
  :<|> "twirp" :> "twirp.example.haberdasher.Health" :> HealthService headers

type HaberdasherService headers
  =    "MakeHat" :> headers :> ReqBody [Protobuf, JSON] Size :> Post '[Protobuf, JSON] Hat 
  :<|> "GetBill" :> headers :> ReqBody [Protobuf, JSON] Hat :> Post '[Protobuf, JSON] Bill

type HealthService headers
  =    "Check" :> headers :> ReqBody [Protobuf, JSON] Ping :> Post '[Protobuf, JSON] Pong
