-- Code generated by protoc-gen-twirp_haskell 0.1.0, DO NOT EDIT.
{-# LANGUAGE TypeOperators #-}
module Haberdasher.Proto.Wrapping where

import Servant
import Twirp

import Haberdasher.Proto.WrappingPB

type WrappingAPI
  =    
