name: Haskell CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.2", "8.4", "8.6", "8.8", "8.10", "9.0", "9.2", "9.4"]

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@968e175ff94d685b6ce0bb39b02447cca8b4a6bb
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v2
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-fused-effects-dist

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --enable-tests
        cabal v2-build     --only-dependencies all

    - name: Build & test
      run: |
        cabal v2-build all
        cabal v2-run twirp-test
        cabal v2-haddock --project-file=cabal.project.ci
        cabal v2-sdist   --project-file=cabal.project.ci
        cabal check
